# Generated by Django 6.0.3 on 2026-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ar',
            field=models.TextField(default='إجابة تجريبية'),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.TextField(default='Sample answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ar',
            field=models.TextField(default='سؤال تجريبي'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(default='Sample question'),
        ),
    ]
