# Generated by Django 6.0.3 on 2026-03-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_answer_text_remove_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default='فئة تجريبية', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='Sample Category', max_length=255),
        ),
    ]
